### ISSUE TITLE
Inline Javascript gets broken via injected CDATA elements

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#176]
For some reason, under some (but not all) circumstances, Transphporm is wrapping my Inline Javascript with CDATA.  This means both my Javascript gets broken, and my browser's console spews error messages like this one:

> SyntaxError: Unexpected token '<' (anonymous function) — list-claims-form:168

The content at that point looks like this:

```xml
    <script><![CDATA[
        $("#payer-id-input").keyup(function (e) {
            var code = (e.keyCode ? e.keyCode : e.which);
            if (code == 39) { // right-arrow keycode
                e.preventDefault();
                $('#payer-picker-modal').modal();
            }
        });
    ]]></script>
```

I've got a working test case where the error is repeatable, although it's still larger than what would be easily posted here.  I'll ZIP it up and attach it, if I can.

**Comment by cxj** [comment]
[test.zip](https://github.com/Level-2/Transphporm/files/1549665/test.zip)

This is kind of large because it contains the vendor structure created by Composer so that this test case can be self-contained.  One could remove the `./vendor/` subdir and adjust the `require` statement to point to one's Transphporm install as needed.

**Comment by cxj** [comment]
I've noticed that this error is frequently introduced when the XML parser doesn't like something but doesn't throw a fatal error, either.  For example, if one uses the HTML entity code `&times;` instead of the XML entity code `&#215;`, this will happen.  As a result, I've written a very simple XML linter to find these. 

I've checked my files with my linter, and they all pass with no errors when run in non-pedantic mode.  In pedantic mode, however, PHP's XML parsing (or more precisely, `libxml`'s parsing) hates all `<script>` tags as being "extra content".  Here's the output from my linter:
```sh
$ lintxml -v !$
lintxml -v list-claims-form.xml
Reading from file list-claims-form.xml
<script>
-^
Fatal Error 5: Extra content at the end of the document
  Line: 256
  Column: 1
```

**Comment by TomBZombie** [comment]
It seems to be if it's loaded as HTML but saved as XML that this happens:
```
<?php
//load HTML and save XML with HTML
$xml = '<html>
	<head>
		<script>
			alert(1);
		</script>
	</head>
	<body>
		foo&nbsp;bar
	</body>
</html>';

$doc = new \DomDocument();

$doc->loadHTML($xml, LIBXML_NOCDATA);

echo $doc->saveXML(null, LIBXML_NOCDATA);

```

`loadXML` paired with `saveHTML` works as expected.  However, I can't see how this ever happens in transphporm, as it pairs the loading/saving method.

**Comment by TomBZombie** [comment]
Using completely valid XML works:

```php
<?php

require 'vendor/autoload.php';

$xml = '<html>
	<head>
		<script>
			alert(1);
		</script>
	</head>
	<body>
		foo
	</body>
</html>';

$transphporm = new \Transphporm\Builder($xml);
echo $transphporm->output()->body;
```

As does invalid XML that will be parsed as HTML:

```php
<?php

require 'vendor/autoload.php';

$xml = '<html>
	<head>
		<script>
			alert(1);
		</script>
	</head>
	<body>
		foo&nbsp;bar
	</body>
</html>';

$transphporm = new \Transphporm\Builder($xml);
echo $transphporm->output()->body;
```

I think it must be to do with including one template in another.

Include invalid HTML parsed document inside XML parsed document:

```php
<?php

require 'vendor/autoload.php';

$xml = '<html>
	<head>
		<script>
			alert(1);
		</script>
	</head>
	<body>
		<div>
		</div>
	</body>
</html>';

$tss = 'div {content: template("invalidxml.xml"); }';


$transphporm = new \Transphporm\Builder($xml, $tss);
echo $transphporm->output()->body;


```

where invalidxml.xml is  `<span>foo&nbsp;bar</span>`

Works.

Loading valid XML into document parsed as XML:

```php
<?php

require 'vendor/autoload.php';

$xml = '<html>
	<head>
		<script>
			alert(1);
		</script>
	</head>
	<body>
		This will be loaded as&nbsp;HTML
		<div>
		</div>
	</body>
</html>';

$tss = 'div {content: template("validxml.xml"); }';


$transphporm = new \Transphporm\Builder($xml, $tss);
echo $transphporm->output()->body;

```

Where validxml.xml is `<span>foo</span>`

Works as intended.

**Comment by TomBZombie** [comment]
Ok I found the problem, it's if the script tag is included:

```php
<?php

require 'vendor/autoload.php';

$xml = '<html>
	<head>

	</head>
	<body>
		This will be loaded as XML
	</body>
</html>';

$tss = 'head {content: template("headvalid.xml"); }';


$transphporm = new \Transphporm\Builder($xml, $tss);
echo $transphporm->output()->body;
```

where `headvalid.xml` is 

```
<?xml version="1.0"?>
<template>
<title>Valid head</title>
<script>
	alert(1);
</script>
</title>
```

Weirdly, both documents are valid XML so I'm not sure why this happens

**Comment by TomBZombie** [comment]
I've found the primary cause of this happening, but I can't see why in src/Template.php:

```php
	/** Loads a HTML or XML document */
	private function loadDocument($doc) {
		libxml_use_internal_errors(true);
		if ($this->document->loadXml($doc) === false) {
			echo 'loading as HTML' . "\n";
				//If HTML is loaded, make sure the document is also saved as HTML
				$this->save = function($content = null) {
					echo 'saving as HTML' . "\n";
					return $this->document->saveHtml($content);
				};
				$this->document->loadHtml('<' . '?xml encoding="UTF-8">' . $doc,  LIBXML_HTML_NODEFDTD | LIBXML_HTML_NOIMPLIED);

				if (strpos($doc, '<!') !== 0) {
					$templateNode = $this->document->getElementsByTagName('template')[0];
					$this->document->replaceChild($templateNode, $this->document->documentElement);
				}
				return;
		}
		else {
			echo 'loading as XML'. "\n";
					//XML was loaded, save as XML.
			$this->save = function($content = null) {
				echo 'saving as XML' . "\n";
				return $this->document->saveXml($content, LIBXML_NOEMPTYTAG);
			};	

		}

		libxml_clear_errors();
	}
```

The `$this->save` closure is set depending on how the document is loaded but the output I get above is:

```
loading as XML
loading as HTML
saving as XML
saving as XML
```

It correctly shows one HTML load and one XML load, but both are being saved as XML and I'm not quite sure why.

**Comment by TomBZombie** [comment]
Here is a minimal example of what's going on:


```php
<?php


$xml = '<html>
	<head>

	</head>
	<body>
		This will be loaded as XML
	</body>
</html>';



$doc1 = new \DomDocument();
$doc1->loadXML($xml);

$html = '<title>Test</title>
<script>
	alert(1);
</script>
';


$doc2 = new \DomDocument();

$doc2->loadHTML($html, LIBXML_HTML_NODEFDTD | LIBXML_HTML_NOIMPLIED);


$script = $doc2->documentElement->getElementsByTagName('script')[0];


$scriptImported = $doc1->importNode($script, true);

$head = $doc1->documentElement->getElementsByTagName('head')[0];

$head->appendChild($scriptImported);

var_dump($doc1->saveXml());
```

We need some way to import the node as XML rather than HTML. `importNode` causes a conversion from HTML to XML and adds the CDATA tag.

**Comment by TomBZombie** [comment]
However we handle this will introduce a different set of potential issues:

### Solution 1:  Using `loadHTML` and `saveHTML` throughout and never using `loadXML` and `saveXML`:

1. Makes things a bit easier but causes problems when dealing with real XML and I'd rather not lose this functionality. It would make, for example, using Transphporm to create an RSS feed needlessly difficult.

2. Translates entities. Using the test I just added, the `&nbsp;` is converted to the actual character in the output, other entities I tried e.g. `&copy` were also converted to the UTF-8 characters e.g. `©`. Not really a problem, but not what you'd probably expect to happen. Looks like this is avoidable though: https://stackoverflow.com/questions/7343284/preventing-domdocumentloadhtml-from-converting-entities

### Solution 2: When a HTML document is imported into an XML document, switch to HTML output

1. This causes a few problems we ran into previously. When using loadXML with saveHTML it causes a few inconsistencies between the input and output

2. It converts entities into XML. `&nbsp;` in the input becomes `&#xA0;` in the output.  Again, doesn't break anything but isn't really desirable behaviour.

### Solution 3: Use HTML throughout unless an `<?xml` tag is present in the document.

1. This will break backwards compatibility. Anyone relying on the behaviour using XML will need to ensure all their documents have an XML tag

2.  We will need to  rewrite ~20 tests which expect XML output e.g.  `<input type="text" />" instead of "<input type="text">"

3. The input may not match the output. You can use `<input type="text" />` in the input, but it won't appear like that in the output

4. This problem will still exist if your parent document has a `<?xml` tag and the imported document does not. 

### Solution 4: str_replace CDATA tags out of the output

1. It's a crude hack

2. It will cause issues if anyone using XML does have genuine CDATA elements in their document (though I imagine this is a very very rare use-case)




Personally I think solution 3, requiring XML documents to have an XML tag is the  preferable option, even if it means rewriting a load of tests.  I will create a branch with this fix to check it doesn't cause any additional issues.

**Comment by TomBZombie** [comment]
The solution on stackoverflow isn't simple. Doing this we would need to put up with converted entities in the document.

**Comment by TomBZombie** [comment]
Using `saveHTML` seems to break this test:

```php
	public function testUTF8() {
		$xml = "<p>this is half english and половина России &</p>";
		$template = new Builder($xml);

		$this->assertEquals('<p>this is half english and половина России &amp;</p>', $template->output()->body);
	}
```

**Comment by TomBZombie** [comment]
I've implemented these changes into the branch Explicit-XML.

In this branch

- Strict XML parsing is only triggered if the document has an xml tag: `<?xml version="1.0?>`
- Entities are automatically converted in the output (`&copy;` in the input becomes `©` in the output)
- Output is always HTML `<br>` instead of `<br />` regardless of input

**Comment by cxj** [comment]
Thank you for all of the attention to and work on this issue.  I lean towards preferring your Solution 3 in my work so far, but I'm of course not the only user.

Can a user of Transphporm intentionally use all HTML as input templates?  I vaguely recall trying that and having some problems with things like HTML entities, e.g. `&copy;`.

Once I have a clearer understanding of what properly, works I'd be happy to provide some canonical examples of proper inputs in the Wiki pages here.  Thanks again.

**Comment by TomBZombie** [comment]
> Can a user of Transphporm intentionally use all HTML as input templates? I vaguely recall trying that and having some problems with things like HTML entities, e.g. &copy;.

The way it worked before, no. The issue was that it would try to parse the document as XML, if that failed, it parsed it as HTML. This caused the issue you ran into because it sometimes resulted in mixing HTML and XML parsed documents. 

It's now the other way around: It will use HTML unless the document starts with `<?xml`.  I think this is the best of both worlds approach in spite of the minor inconveniences this introduces. If you need strict output you can force everything into XML mode by providing the XML tag.

**Comment by cxj** [comment]
I actually don't care which flavor of input I need to use as long as it is consistent.  To me, I'm building Transphporm templates to generate HTML5 for use by modern browsers.  That the input templates look like HTML or XML is just a wonderful convenience.

I just updated from `a227407` to dev-master `f029dd3` with your fixes and now I'm getting stack backtraces because of:

`Notice: Array to string conversion in staging/vendor/level-2/transphporm/src/Property/ContentPseudo/Attr.php on line 10`

Since I'm using several partials, the problem could be in one of 3 TSS files and 4 XML files.  :-(

**Comment by TomBZombie** [comment]
Hmm, the changes I made should not have affected `:attr()`.

Can you post any TSS you have that sets an attribute, e.g.

```css
div:attr(class) {...}

```

**Comment by cxj** [comment]
Can do.  Let me gather it.

**Comment by cxj** [comment]
I think these may be the primary 3 culprits.  The page where I saw this error has 3 `<select>`-style lists which are populated dynamically from the database using the following TSS code snippets:
```css
/* Claim Filing Status select/dropdown box */
.filing_indicator option {
    repeat: data(output.claimFilingStatus);
}
.filing_indicator option:attr(value) {
    content: key();
}
.filing_indicator option {
    content: iteration();
}

/* PWK Status select/dropdown box */
.pwk_status option {
    repeat: data(output.paperworkAttachment);
}
.pwk_status option:attr(value) {
    content: key();
}
.pwk_status option {
    content: iteration();
}

/* Claim Status select/dropdown box */
.clx_status option {
    repeat: data(output.claimStatus);
}
.clx_status option:attr(value) {
    content: key();
}
.clx_status option {
    content: iteration();
}
```

**Comment by TomBZombie** [comment]
Well found, I've managed to replicate this issue:

```php
		$xml = '<select><option></option></select>';

		$tss = 'select option {repeat: data(options); }
		select option { content: iteration(); }
		select option:attr(value) { content: key(); }
		';

		$template = new Builder($xml, $tss);

		$data = ['options' => [
				'01' => 'January',
				'02' => 'Februrary',
				'03' => 'March'
		]];

		$output = $template->output($data)->body;

		var_dump($output);
```

It appears to be `key()` that causes the issue

**Comment by cxj** [comment]
Strange that a change for XML/HTML would affect `key()`, at least to my way of thinking.  Glad you were able to create a small test case which duplicates the problem.

**Comment by TomBZombie** [comment]
I've found the commit which broke this: https://github.com/Level-2/Transphporm/commit/8a12d1680ca8ca060020b9491121009e86065d20

It was one concerning that class

**Comment by TomBZombie** [comment]
I'm surprised this issue never came up earlier, the way the rules were sorted was wrong a lot of the time! It was doing `select option {}` before `select option:attr() {` so when it tried to set the attribute value, `key()` was never set because it hadn't yet run `repeat`.

**Comment by cxj** [comment]
Grabbing `dev-master` and testing soon.

**Comment by cxj** [comment]
My stand-alone command line test passes, but my full web does not (same error as before).  The first `<option>` tag comes out looking like this:
```html
<option value="Array"></option>
```
The `value` should be an empty string; PHP is putting the word "Array" in there to indicate it got an array for the value.

I'm setting a "blank" or "not yet selected" first option by placing this value on the front of the array I use to populate it during Transphporm's TSS animation:
```php
$claimFilingStatus = [
     0    => "",
     "11" => "11 = Other Non-Federal Programs",
     "12" => "12 = (PPO)",
     "13" => "13 = (POS)",
     // etc.
```
So is there a chance that 0 index is the cause?

**Comment by TomBZombie** [comment]
It's not the blank option that causes a problem:

```php

	$xml = '<select><option></option></select>';

		$tss = 'select option {repeat: data(options); }
		select option { content: iteration(); }
		select option:attr(value) { content: key(); }
		';

		$template = new Builder($xml, $tss);

		$data = ['options' => [
				0 => '',
				'01' => 'January',
				'02' => 'Februrary',
				'03' => 'March'
		]];

		$output = $template->output($data)->body;

```

Gives me:

```
<select><option value="0"></option><option value="01">January</option><option value="02">Februrary</option><option value="03">March</option></select>
```
as expected. I also tried with `''` and `null` as both key and value.

**Comment by TomBZombie** [comment]
Actually something isn't right:

```php
	$data = ['options' => [
				null => null,
				'01' => 'January',
				'02' => 'Februrary',
				'03' => 'March'
		]];

```

Gives 


```
<select><option value="">JanuaryFebruraryMarch</option><option value="01">January</option><option value="02">Februrary</option><option value="03">March</option></select>
```

**Comment by TomBZombie** [comment]
Can you let me know if this patch fixes it:

```patch
diff --git a/src/Hook/ElementData.php b/src/Hook/ElementData.php
index 0c405b9..b6702eb 100644
--- a/src/Hook/ElementData.php
+++ b/src/Hook/ElementData.php
@@ -17,6 +17,7 @@ class ElementData {
 
        /** Binds data to an element */
        public function bind(\DomNode $element, $data, $type = 'data') {
+               if ($data === null) $data = '';
                $content = isset($this->elementMap[$element]) ? $this->elementMap[$element] : [];
                $content[$type] = $data;
                $this->elementMap[$element] = $content;
```

It shouldn't because you're using an empty string instead of `null` but it might be the same root cause.

**Comment by cxj** [comment]
Will do.

**Comment by TomBZombie** [comment]
Yes, I think this is the problem. Possibly different on different PHP versions too:

In `Parser\Value` there's the line:

```php
		$this->data = new ValueData($data ? $data : $this->baseData);
```

*if no data is  set for this specific element, use the main data object from the output function*. That means, if an element's data is set to `null` it will use the main data array rather than `null`. 

And it depends on how PHP interprets ` $expr ? `  does it do `$expr == null` or `$expr === null` behind the scenes?

**Comment by cxj** [comment]
Ah.  I'm running PHP 7.1.8, for what it's worth.

**Comment by TomBZombie** [comment]
I've fixed that in the latest commit with `array_key_exists` instead of `isset`. Let me know if that fixes it, it looks like the same issue.

**Comment by cxj** [comment]
It's not looking good.  Still getting "Array to string conversion" errors.  I'm looking further and trying to make a small test case which replicates the problem.

**Comment by cxj** [comment]
I've got a fairly small test case which duplicates the error.  I'm just trying to shrink it a bit more so I can package it neatly to post here.

**Comment by cxj** [comment]
PHP (e.g. test.php):
```php
<?php
require "vendor/autoload.php";

$xml = 'default_base_layout.xml';
$tss = 'list-claims-form.tss';
$tpl = new Transphporm\Builder($xml, $tss);


$data['output'] = array(
                    'claimFilingStatus' => array(
                        0    => '',
                        '01' => 'January',
                        '02' => 'Februrary',
                        '03' => 'March'
                    )
                );

echo $tpl->output($data)->body . PHP_EOL;
```

default_base_layout.xml:
```xml
<!DOCTYPE html>
<html xml:lang="en" lang="en">
<head> <title>Error Demonstration</title> </head>
<body>
<main class="container">
    Main
</main>
</body>
</html>
```
list-claims-form.tss:
```css
main {
    content: template("list-claims-form.xml");
}

.filing_indicator option {
    repeat: data(output.claimFilingStatus);
}
.filing_indicator option:attr(value) {
    content: key();
}
.filing_indicator option {
    content: iteration();
}
```
list-claims-form.xml:
```xml
<form>
    <div class='filing_indicator'>
        <select>
            <option value="1">Option One Placeholder</option>
        </select>
    </div>
</form>
```

**Comment by TomBZombie** [comment]
Do you know off hand if it still causes the error without the included template? If not don't worry I'll test it myself.

**Comment by cxj** [comment]
I've not tested that situation, no.

**Comment by TomBZombie** [comment]
ok I've managed to minimise it to:

```php
		$xml = '<form>
    <div class="filing_indicator">
        <select>
            <option value="1">Option One Placeholder</option>
        </select>
    </div>
</form>';

			
		$tss = '.filing_indicator option {
		    repeat: data(output.claimFilingStatus);
		}
		.filing_indicator option:attr(value) {
		    content: key();
		}
		.filing_indicator option {
		    content: iteration();
		}';


		$data['output'] = array(
                    'claimFilingStatus' => array(
                        0    => '',
                        '01' => 'January',
                        '02' => 'Februrary',
                        '03' => 'March'
                    )
                );


		$template = new Builder($xml, $tss);

		$output = $template->output($data)->body;
```

**Comment by TomBZombie** [comment]
Ok I've found the source of the issue but not the cause. Swapping the order :

```css
.filing_indicator option {
    repeat: data(output.claimFilingStatus);
}
.filing_indicator option:attr(value) {
    content: key();
}
.filing_indicator option {
    content: iteration();
}
```

to

```css

.filing_indicator option {
    repeat: data(output.claimFilingStatus);
}

.filing_indicator option {
    content: iteration();
}

.filing_indicator option:attr(value) {
    content: key();
}
```

works

**Comment by garrettw** [comment]
To address a prior comment, if I'm not mistaken, `$expr ?` is the same as `$expr == true`. This is why I've moved to explicit expressions instead of truthy/falsy stuff.

**Comment by garrettw** [comment]
Is there a way this could be handled such that the repeat's position in the source code doesn't matter?
If not, I think this scenario would be a good candidate for a friendly error message saying something like "Error: iteration() called before specifying what to repeat".

**Comment by TomBZombie** [comment]
This will now work:

```css

.filing_indicator option {
    repeat: data(output.claimFilingStatus);
}

.filing_indicator option:attr(value) {
    content: key();
}
.filing_indicator option {
    content: iteration();
}
```

But this won't:


```css
.filing_indicator option:attr(value) {
    content: key();
}

.filing_indicator option {
    repeat: data(output.claimFilingStatus);
}
```
This used to work,  the problem is, we stopped counting pseudo selectors as an indicator of depth in #166 

You might  say "then count :attr() but not :before" but that just moves the issue, you then couldn't use `key()` or `iteration()` e.g.  `foo:before {content: key(); }` if that line was before setting repeat.

But yes, I think it's a good idea to have a sanity check on it.

**Comment by cxj** [comment]
I can confirm that combining like-named rules fixes my problem, i.e.:
```css
.filing_indicator option {
    repeat: data(output.claimFilingStatus);
    content: iteration();
}
```
I probably would have written the rules that way to begin with but something about the `repeat` pulling data made me feel it wouldn't work, so I never tried.  :-p

**Comment by TomBZombie** [comment]
The latest commit should work with your original code as well.

**Comment by TomBZombie** [comment]
Actually I think I can improve the sorting algorithm:

- Sort like it does currently
- But if there are `foo` and `foo:bar` move `foo:bar` to the end.

**Comment by cxj** [comment]
I can confirm changes up to commit 319ec0f appear to work with TSS like the following:
```css
.filing_indicator option {
    repeat: data(output.claimFilingStatus);
}
.filing_indicator option:attr(value) {
    content: key();
}
.filing_indicator option {
    content: iteration();
}
```

Sorry I was not able to respond earlier.  I had a previously arranged engagement.  Thanks again for all the quick fixes and improvements.

**Comment by TomBZombie** [comment]
No worries, glad to help. I'm trying to squash as many bugs in the library as I can while I have the time! If you find any more please post them!
